apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bar-app
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SomasekharSunkari/Argocd-check.git
    targetRevision: HEAD
    path: environment/staging/app2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - Createnamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
